#!/usr/bin/env node
/**
 * 🧠 Semantic Distiller v1.1
 * Purpose: Analyzes daily logs using LLM and updates WISDOM.md with new patterns and lessons.
 * Improvements: Multi-day analysis, deeper context from memory/archive/.
 */
const fs = require('fs');
const path = require('path');
const router = require('../survival/model_cascade_router');

const ROOT = '/root/.openclaw/workspace';
const WISDOM_PATH = path.join(ROOT, 'docs/architecture/WISDOM.md');
const MEMORY_DIR = path.join(ROOT, 'memory');

async function getRecentLogs(days = 3) {
    const files = fs.readdirSync(MEMORY_DIR)
        .filter(f => f.match(/^\d{4}-\d{2}-\d{2}\.md$/))
        .sort()
        .reverse()
        .slice(0, days);
    
    if (files.length === 0) return "";
    
    let combinedLogs = "";
    for (const file of files) {
        combinedLogs += `--- LOG: ${file} ---\n`;
        combinedLogs += fs.readFileSync(path.join(MEMORY_DIR, file), 'utf8') + "\n\n";
    }
    return combinedLogs;
}

async function runDistillation() {
    console.log("🧠 Semantic Distiller v1.1 starting cycle...");
    
    const logs = await getRecentLogs(3);
    if (!logs) {
        console.log("No logs found to distill.");
        return;
    }

    if (!fs.existsSync(WISDOM_PATH)) {
        fs.mkdirSync(path.dirname(WISDOM_PATH), { recursive: true });
        fs.writeFileSync(WISDOM_PATH, "# 🧠 WISDOM.md - Jarvis Experience & Patterns\n\n## Core Patterns\n\n## Lessons Learned\n\n---\n*Generated by Jarvis Semantic Distiller.*\n");
    }

    const currentWisdom = fs.readFileSync(WISDOM_PATH, 'utf8');

    const prompt = `
You are the Semantic Distiller for Jarvis.
Your task is to analyze the recent activity logs and extract 1-2 NEW high-level patterns (P-XXX) or lessons learned (L-XXX).
Patterns are recurring behaviors or system dynamics. Lessons are specific technical or operational mistakes/fixes.

CURRENT WISDOM:
${currentWisdom}

RECENT LOGS (Last 3 days):
${logs}

OUTPUT FORMAT:
Return ONLY the new entries in Markdown format (bullet points). Do not include any other text or greetings.
Example:
- **P-005 (Performance):** High session count (>30) leads to gateway scheduling delays.
- **L-004:** Always remove 'immutable' flags before attempting to move core protocol files.
`;

    try {
        const result = await router.think(prompt, { model: 'gemini-3-pro-preview' });
        
        if (result.error || !result.text) {
            console.error("Distillation failed: brain rejected or empty response.");
            return;
        }

        const newEntries = result.text.trim();
        if (newEntries.length < 10) {
            console.log("No significant new wisdom distilled today.");
            return;
        }

        const lines = currentWisdom.split('\n');
        const footerIndex = lines.findIndex(l => l.includes('---'));
        
        if (footerIndex !== -1) {
            lines.splice(footerIndex, 0, newEntries + '\n');
        } else {
            lines.push('\n' + newEntries);
        }

        const updatedWisdom = lines.join('\n');
        fs.writeFileSync(WISDOM_PATH, updatedWisdom);
        
        console.log("✅ WISDOM.md updated with new insights.");
        console.log("New Insights:\n" + newEntries);

    } catch (e) {
        console.error(`Distillation error: ${e.message}`);
    }
}

runDistillation();
